testing

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -15,14 +15,14 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '16.0.0' # Use a stable version of Node.js
+          node-version: '18.19.0' # Use a compatible version of Node.js
 
       - name: Install dependencies
         run: npm install
 
       - name: Build Angular app
         run: |
-          npm run build --prod || (cat /root/.npm/_logs/*-debug.log && false) # Output npm debug log on failure
+          npm run build --prod || (cat /home/runner/work/_temp/_github_home/_npm/_logs/*-debug.log && false) # Output npm debug log on failure
 
       - name: Build Docker image
         run: |
